const COUNTRY_NAMES: Record<string, string> = {
  US: "United States",
  GB: "United Kingdom",
  DE: "Germany",
  FR: "France",
  CA: "Canada",
  AU: "Australia",
  IN: "India",
  BR: "Brazil",
  NL: "Netherlands",
  JP: "Japan",
  SE: "Sweden",
  ES: "Spain",
  IT: "Italy",
  PL: "Poland",
  MX: "Mexico",
  KR: "South Korea",
  CN: "China",
  SG: "Singapore",
  IE: "Ireland",
  CH: "Switzerland",
  NO: "Norway",
  DK: "Denmark",
  FI: "Finland",
  BE: "Belgium",
  AT: "Austria",
  PT: "Portugal",
  NZ: "New Zealand",
  ZA: "South Africa",
  AR: "Argentina",
  ID: "Indonesia",
  PH: "Philippines",
  TH: "Thailand",
  VN: "Vietnam",
  TR: "Turkey",
  IL: "Israel",
  AE: "United Arab Emirates",
  NG: "Nigeria",
  EG: "Egypt",
  UA: "Ukraine",
  CZ: "Czechia",
  RO: "Romania",
  HU: "Hungary",
  GR: "Greece",
  CL: "Chile",
  CO: "Colombia",
  PE: "Peru",
  MY: "Malaysia",
  HK: "Hong Kong",
  TW: "Taiwan",
  RU: "Russia",
};

export function countryName(code: string): string {
  return COUNTRY_NAMES[code.toUpperCase()] ?? code.toUpperCase();
}
